### ISSUE TITLE
Maturin integration is not compatible with python lint and unit tests

### ISSUE THREAD

**Issue by Tpt** [kraken-build/kraken-std#34]
It would be nice to install automatically a development version of the Rust Python libraries using `maturin develop` before running flake8, mypy and Python unit tests to allow writing e.g. integration tests in Python.

**Comment by NiklasRosenstein** [comment]
Sounds like we could do that by overriding `PoetryPythonBuildSystem.install()` in `MaturinPythonBuildSystem` and make it run `maturin develop`. 👍 

https://github.com/kraken-build/kraken-std/blob/develop/src/kraken/std/python/buildsystem/poetry.py#L165
